commander-rb/commander

- lib/commander/help_formatters/terminal/help.erb
- lib/commander/help_formatters/terminal_compact/help.erb
By using the longest command and alias names to determine how much to
"indent" the descriptions.
Re-opened from https://github.com/tj/commander/issues/98
> Fix command formatting for commands with long names

- lib/commander/import.rb
- lib/commander/methods.rb
If a terminal reports it's screen width as < 5, wrap_at could become negative causing Highline to enter an infinite loop whilst wrapping.
This makes sure we don't set negative wrap_at values by ensuring the terminal screen width at least 5.
It also cleans up the duplicated code.
> Fix negative Highline wrap

- lib/commander/help_formatters/terminal/command_help.erb
9ea5c0f added indentation of program and command descriptions. However, I've found myself also sometimes wanting multiline option descriptions, like the `-u` option from `git-commit` have (shown below). This patch adds identing of option descriptions.
```
-u[<mode>], --untracked-files[=<mode>]
Show untracked files.
The mode parameter is optional (defaults to all), and is used to specify the handling of untracked files; when -u is not used, the default is normal, i.e. show untracked files and directories.
The possible options are:
·   no - Show no untracked files
·   normal - Shows untracked files and directories
·   all - Also shows individual files in untracked directories.
The default can be changed using the status.showUntrackedFiles configuration variable documented in git-config(1). …
```
> Multiline option descriptions

- lib/commander/user_interaction.rb
> Fix deprecation warning on ruby 2.3.0

- .rubocop_todo.yml
- lib/commander/runner.rb
- spec/runner_spec.rb
Addresses #27 by ensuring that option switches of the style '--[no-]blah' are expanded into their '--blah' and '--no-blah' possibilities before checking against arguments to remove in `remove_global_options`
> Fix handling of '--[no-]blah' style flags for global_option

- lib/commander/runner.rb
- spec/runner_spec.rb
Fixes #29 
@mariusmarais I think this should fix the problem you reported.
> Allow options that start with a global option name

- lib/commander/user_interaction.rb
The `MissingSourceFile` constant is added to the list of constants to
ignore because of the deprecation warnings that their usage cause.
With ActiveSupport 5+, `MissingSourceFile` has been deprecated and will
now throw warnings.
This is fixes [Issue 36](https://github.com/commander-rb/commander/issues/36)
> Fix Issue 36 - Ignore MissingSourceFile

- lib/commander/runner.rb
- spec/runner_spec.rb
- spec/spec_helper.rb
Adds a flag for toggling `help` command paging behaviour.
It doesn't change the defaults.
Depends on https://github.com/commander-rb/commander/pull/40
> help command - add paging flag

- lib/commander/user_interaction.rb
To fix https://github.com/commander-rb/commander/issues/41
> Ignore constants deprecated in Ruby 2.4

- .travis.yml
- commander.gemspec
- lib/commander/user_interaction.rb
This PR fixes the following warning on Ruby 2.5.0:
> commander-4.4.3/lib/commander/user_interaction.rb:334: warning: constant ::Data is deprecated
Also:
* Add Ruby 2.5.0 to Travis
* Change other Travis Rubies to their latest patch versions
* Enable Bundler cache on Travis
* Pin RuboCop at 0.49 (0.50 and above don't support Ruby 1.9 syntax)
Fixes #61
> Fix Ruby 2.5.0 warning; add latest Rubies to Travis

- lib/commander/user_interaction.rb
- spec/methods_spec.rb
Related to #62 — here is a way we can avoid triggering deprecation warnings for most users as new constants become deprecated in future versions of Ruby. This patch defers scanning all constants until an `ask_for_*` method is actually called.
@mattbrictson @rous-gg @rlgomes please review if you're interested :)
> Avoid deprecation warnings on load

- lib/commander/command.rb
- spec/command_spec.rb
This revises d4fd7a53fa2c4bba7a72e0ecdbe4d56a59039de9 to maintain the
proxy_options / proxy_options_struct data after running a command, while
still avoiding the issue of entries accumulating in proxy_options over
multiple runs.
> Empty proxy_options before parse

- commander.gemspec
- lib/commander/core_ext/array.rb
- lib/commander/help_formatters/terminal/command_help.erb
- lib/commander/help_formatters/terminal/help.erb
- lib/commander/methods.rb
- lib/commander/runner.rb
- lib/commander/user_interaction.rb
- spec/methods_spec.rb
- spec/spec_helper.rb
The currently used version of `HighLine` is 1.7.2, which was released mid-2015. This PR updates `HighLine` to the latest version (`2.0.0`).
This version of `HighLine` currently passes tests on all ruby versions listed in [.travis.yml](https://github.com/commander-rb/commander/blob/master/.travis.yml#L6). However, ruby `1.9.3` doesn't seem to be 'officially' supported, `HighLine`'s `.travis.yml` [allows failures on `1.9.3`](https://github.com/JEG2/highline/blob/bf489b632afd92c68df0b2c1f348afb66b5495aa/.travis.yml#L19-L24).
> Update highline dependency

- commander.gemspec
Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `homepage_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/commander), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.
> Add project metadata to the gemspec

- lib/commander/command.rb
- lib/commander/runner.rb
- spec/command_spec.rb
- spec/runner_spec.rb
As detailed in #86, global options are ignored when command specific options or arguments are provided.
Separate the global options from the command specific options. This prevents the global options from being cleared when the command specific options are parsed.
Fixes #86.
> Fix: Global option values ignored when args provided

- lib/commander/runner.rb
- spec/runner_spec.rb
In issue #32, it is reported that global options are not available at command level when placed before command name. I found this to be a defect in the identification of command names from arguments.
https://github.com/commander-rb/commander/blob/0abbac486ea7d87f6f680aaf17d0e3cd136dbf73/lib/commander/runner.rb#L248-L251
This method was not correctly accounting for global options with provided values. ie. in the example provided by @msabramo:
```sh
aptly-cli --server 10.3.0.46 repo_list
```
It would incorrectly determine the `args_string` to be `"10.3.0.46 repo_list"` thus expecting the command name to start with `10.3.0.46`.
I propose the `valid_command_names_from` method be modified to remove all global options from the args. This way it correctly identify the command name(s).
This will …
> Fix command name identification

- lib/commander/runner.rb
I notice there's no need to mutate the `switches` array.
https://github.com/commander-rb/commander/blob/0abbac486ea7d87f6f680aaf17d0e3cd136dbf73/lib/commander/runner.rb#L336
As only first portion of each switch is compared to the argument.
https://github.com/commander-rb/commander/blob/0abbac486ea7d87f6f680aaf17d0e3cd136dbf73/lib/commander/runner.rb#L344
I propose to remove this mutation.
> Small optimisation of remove_global_options

- lib/commander/help_formatters/terminal.rb
- lib/commander/help_formatters/terminal_compact.rb
Try no. 2 to fix Ruby v2.7 warnings.
```
~/.gem/ruby/2.7.0/gems/commander-4.5.1/lib/commander/help_formatters/terminal.rb:15: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
~/.gem/ruby/2.7.0/gems/commander-4.5.1/lib/commander/help_formatters/terminal.rb:15: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
```
> Fix ERB for Ruby v2.7 warnings (no. 2)

- lib/commander/runner.rb
- spec/runner_spec.rb
As identified in #47, global options are not removed from the command options when provided in the form `option=value`. This results in an invalid option error when parsing the command specific options.
Proposed in this PR is an implementation to fix this.
Fixes #47.
> Correctly handle global options provided in the option=value form

- lib/commander/runner.rb
- spec/runner_spec.rb
It is reported in #94 that using `--help` after a command name and command argument does not work.
```
$ mycli command-name command-arg --help
invalid command. Use --help for more information
```
Investigation finds the `help` command is assuming the the command name is all the arguments joined together.
https://github.com/commander-rb/commander/blob/b8abd42153118ca9fdc02affeb9f3aab61cda5a2/lib/commander/runner.rb#L307
Fix #94 by changing the line in question to ignore the command argument when searching for command name. Just take the longest valid command name found in the arguments.
This also changes the behaviour of the help command in its alternate form. This will ignore the argument and provide the documentation for the specified command, where previously it would give an error …
> Use --help after command and argument
